import i18next from 'i18next';
import ru from './navigation-i18n/ru';
import am from './navigation-i18n/am';
import en from './navigation-i18n/en';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('ru', 'navigation', ru);
i18next.addResourceBundle('am', 'navigation', am);

const navigationConfig = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    subtitle: '',
    name: 'Dashboards',
    type: 'group',
    icon: 'heroicons-outline:home',
    translate: 'DASHBOARDS',
    children: [
      {
        id: 'dashboards',
        title: 'DASHBOARDS',
        translate: 'DASHBOARDS',
        name: 'Dashboards',
        type: 'item',
        icon: 'heroicons-outline:chart-pie',
        url: '/dashboard',
        children: null,
      },
      {
        id: 'logo-component',
        title: 'Logo',
        name: 'Logo',
        translate: 'SETTINGS',
        type: 'item',
        icon: 'material-twotone:settings',
        url: 'view/logo',
        children: null,
      },
      {
        id: 'fileManager-component',
        title: 'FileManager',
        name: 'FileManager',
        translate: 'FILEMANAGER',
        type: 'item',
        icon: 'material-twotone:video_settings',
        url: 'view/fileManager',
        children: null,
      },
    ],
  },
  {
    id: 'projects',
    title: 'Projects',
    subtitle: '',
    name: 'Projects',
    type: 'group',
    icon: 'heroicons-outline:office-building',
    translate: 'PROJECTS',
    children: [
      // {
      //   id: 'projects-component',
      //   title: 'Projects',
      //   translate: 'PROJECTS',
      //   name: 'Projects',
      //   type: 'item',
      //   icon: 'heroicons-outline:office-building',
      //   url: '/projects/item',
      //   children: null,
      // },
      // {
      //   id: 'projects-areas',
      //   title: 'AREAS',
      //   translate: 'AREAS',
      //   name: 'Areas',
      //   type: 'item',
      //   icon: 'material-outline:category',
      //   url: '/projects/areas',
      //   children: null,
      // },
      // {
      //   id: 'projects-status',
      //   title: 'STATUS',
      //   translate: 'STATUS',
      //   name: 'Status',
      //   type: 'item',
      //   icon: 'material-twotone:settings',
      //   url: '/projects/status',
      //   children: null,
      // },
      // {
      //   id: 'projects-regions',
      //   title: 'REGIONS',
      //   translate: 'REGIONS',
      //   name: 'Regions',
      //   type: 'item',
      //   icon: 'heroicons-outline:map',
      //   url: '/projects/regions',
      //   children: null,
      // },
      {
        id: 'projects-categories',
        title: 'CATEGORIES',
        translate: 'CATEGORIES',
        name: 'Categories',
        type: 'item',
        icon: 'heroicons-outline:collection',
        url: '/projects/categories',
        children: null,
      },
    ],
  },
  // {
  //   id: 'news',
  //   title: 'News',
  //   subtitle: '',
  //   name: 'News',
  //   type: 'group',
  //   icon: 'heroicons-outline:newspaper',
  //   translate: 'NEWS',
  //   children: [
  //     {
  //       id: 'news-component',
  //       title: 'News',
  //       translate: 'NEWS',
  //       name: 'News',
  //       type: 'item',
  //       icon: 'heroicons-outline:newspaper',
  //       url: '/news/item',
  //       children: null,
  //     },
  //   ],
  // },
  {
    id: 'pages',
    title: 'Pages',
    name: 'PagesGroup',
    subtitle: 'Pages Base',
    type: 'group',
    icon: 'material-solid:book',
    translate: 'PAGES',
    translate_subtitle: 'PAGES_BASE',
    children: [
      {
        id: 'pages-component',
        title: 'Pages',
        name: 'Pages',
        translate: 'PAGES',
        type: 'item',
        icon: 'material-solid:book',
        url: 'pages',
        children: null,
      },
      {
        id: 'pageTemplates-component',
        title: 'PageTemplates',
        name: 'PageTemplates',
        translate: 'PAGETEMPLATES',
        type: 'item',
        icon: 'material-solid:book',
        url: 'pageTemplate',
        children: null,
      },
    ],
  },
  {
    id: 'view',
    title: 'View',
    name: 'View',
    subtitle: 'Site View',
    type: 'group',
    icon: 'heroicons-outline:home',
    translate: 'SITE_VIEW',
    translate_subtitle: 'SITE_VIEW_DESCRIPTION',
    children: [
      {
        id: 'languages-component',
        title: 'Languages',
        name: 'Languages',
        translate: 'LANGUAGES',
        type: 'item',
        icon: 'material-solid:translate',
        url: 'view/languages',
        children: null,
      },
      {
        id: 'translations-component',
        title: 'Translations',
        name: 'Translations',
        translate: 'TRANSLATIONS',
        type: 'item',
        icon: 'material-solid:g_translate',
        url: 'view/translations',
        children: null,
      },
      {
        id: 'socials-component',
        title: 'Socials',
        name: 'Socials',
        translate: 'SOCIALNETWORKS',
        type: 'item',
        icon: 'feather:globe',
        url: 'view/socials',
        children: null,
      },
      {
        id: 'announcement-component',
        title: 'Announcement',
        name: 'Announcement',
        translate: 'ANNOUNCEMENT',
        type: 'item',
        icon: 'heroicons-solid:newspaper',
        url: 'view/announcement',
        children: null,
      },
      {
        id: 'faq-component',
        title: 'FAQ',
        name: 'FAQ',
        translate: 'FAQ',
        type: 'item',
        icon: 'feather:help-circle',
        url: 'view/faq',
        children: null,
      },
      {
        id: 'menu-component',
        title: 'Menu',
        name: 'Menu',
        translate: 'MENU',
        type: 'item',
        icon: 'material-solid:menu',
        url: 'view/menu',
        children: null,
      },
      {
        id: 'footer',
        title: 'Footer',
        name: 'Footer',
        translate: 'FOOTER',
        type: 'item',
        icon: 'feather:chevrons-down',
        url: 'view/footer/sections',
        children: null,
      },
      {
        id: 'slider-component',
        title: 'Slider',
        name: 'Slider',
        translate: 'SLIDER',
        type: 'item',
        icon: 'material-twotone:video_settings',
        url: 'view/slider',
        children: null,
      },
      {
        id: 'services-component',
        title: 'Services',
        name: 'Services',
        translate: 'SERVICES',
        type: 'item',
        icon: 'material-solid:design_services',
        url: 'view/services',
        children: null,
      },
      {
        id: 'youtube-settings',
        title: 'Youtube',
        name: 'Youtube',
        translate: 'YOUTUBESETTINGS',
        type: 'item',
        icon: 'feather:youtube',
        url: 'view/youtube/settings',
        children: null,
      },
      // {
      //   id: 'STEP',
      //   title: 'STEP',
      //   name: 'STEP',
      //   translate: 'STEP',
      //   type: 'item',
      //   icon: 'material-solid:format_list_numbered',
      //   url: 'view/step',
      //   children: null,
      // },
      // {
      //   id: 'statistics',
      //   title: 'STATISTICS',
      //   name: 'STATISTICS',
      //   translate: 'STATISTICS',
      //   type: 'item',
      //   icon: 'material-twotone:query_stats',
      //   url: 'view/statistics',
      //   children: null,
      // },
      // {
      //   id: 'partners-component',
      //   title: 'Partners',
      //   name: 'Partners',
      //   translate: 'PARTNERS',
      //   type: 'item',
      //   icon: 'heroicons-outline:user-group',
      //   url: 'view/partners',
      //   children: null,
      // },
    ],
  },
  {
    id: 'administartion',
    title: 'Administration',
    name: 'Administration',
    subtitle: 'Administrative Base',
    type: 'group',
    icon: 'material-solid:people',
    translate: 'ADMINISTRATION',
    translate_subtitle: 'ADMINISTRATIVE_BASE',
    children: [
      {
        id: 'admins',
        title: 'Admins',
        name: 'Admins',
        type: 'collapse',
        icon: 'material-solid:people',
        url: '',
        translate: 'ADMINS',
        children: [
          {
            id: 'admins-component',
            title: 'admins',
            name: 'admins',
            translate: 'ADMINS',
            type: 'item',
            icon: 'material-solid:person',
            url: 'administration/admins',
            children: null,
          },
          {
            id: 'roles-component',
            title: 'Roles',
            name: 'Roles',
            translate: 'ROLES',
            type: 'item',
            icon: 'material-solid:admin_panel_settings',
            url: 'administration/roles',
            children: null,
          },
          {
            id: 'permissions-component',
            title: 'Permissions',
            name: 'Permissions',
            translate: 'PERMISSIONS',
            type: 'item',
            icon: 'material-solid:admin_panel_settings',
            url: 'administration/permissions',
            children: null,
          },
        ],
      },
    ],
  },
  {
    id: 'pages',
    title: 'Pages',
    name: 'PagesGroup',
    subtitle: 'Pages Base',
    type: 'group',
    icon: 'material-solid:book',
    translate: 'PAGES',
    translate_subtitle: 'PAGES_BASE',
    children: [
      {
        id: 'pages-component',
        title: 'Pages',
        name: 'Pages',
        translate: 'PAGES',
        type: 'item',
        icon: 'material-solid:book',
        url: 'pages',
        children: null,
      },
      {
        id: 'pageTemplates-component',
        title: 'PageTemplates',
        name: 'PageTemplates',
        translate: 'PAGETEMPLATES',
        type: 'item',
        icon: 'material-solid:book',
        url: 'pageTemplate',
        children: null,
      },
    ],
  },
  {
    id: 'projects',
    title: 'Projects',
    subtitle: '',
    name: 'Projects',
    type: 'group',
    icon: 'heroicons-outline:office-building',
    translate: 'PROJECTS',
    children: [
      {
        id: 'projects-component',
        title: 'Projects',
        translate: 'PROJECTS',
        name: 'Projects',
        type: 'item',
        icon: 'heroicons-outline:office-building',
        url: '/projects/item',
        children: null,
      },
      {
        id: 'projects-areas',
        title: 'AREAS',
        translate: 'AREAS',
        name: 'Areas',
        type: 'item',
        icon: 'material-outline:category',
        url: '/projects/areas',
        children: null,
      },
      {
        id: 'projects-status',
        title: 'STATUS',
        translate: 'STATUS',
        name: 'Status',
        type: 'item',
        icon: 'material-twotone:settings',
        url: '/projects/status',
        children: null,
      },
      {
        id: 'projects-regions',
        title: 'REGIONS',
        translate: 'REGIONS',
        name: 'Regions',
        type: 'item',
        icon: 'heroicons-outline:map',
        url: '/projects/regions',
        children: null,
      },
    ],
  },
  {
    id: 'news',
    title: 'News',
    subtitle: '',
    name: 'News',
    type: 'group',
    icon: 'heroicons-outline:newspaper',
    translate: 'NEWS',
    children: [
      {
        id: 'news-component',
        title: 'News',
        translate: 'NEWS',
        name: 'News',
        type: 'item',
        icon: 'heroicons-outline:newspaper',
        url: '/news/item',
        children: null,
      },
    ],
  },
  {
    id: 'BACKUPES',
    title: 'BACKUPES',
    subtitle: '',
    name: 'BACKUPES',
    type: 'group',
    icon: 'heroicons-outline:archive',
    translate: 'BACKUPES',
    children: [
      {
        id: 'Backup-component',
        title: 'BACKUPES',
        name: 'BACKUPES',
        translate: 'BACKUPES',
        type: 'item',
        icon: 'heroicons-outline:archive',
        url: 'view/backup',
        children: null,
      },
    ],
  },
];

export default navigationConfig;
